--INSERT INTO EXECUTION(PATH, TEST_CASE, STATUS, RESULT) VALUES ("suny.test", "t1", "Started", "");
--INSERT INTO EXECUTION(PATH, TEST_CASE, STATUS, RESULT) VALUES ("suny.test", "t2", "Completed", "Pass")
SELECT 1